/* ═══════════════════════════════════════════════════════════
   app.js — Traduction Contrôle Frontière
   Handles: data, rendering, navigation, TTS, copy, fullscreen
═══════════════════════════════════════════════════════════ */

"use strict";

/* ─────────────────────────────────────────────────────────
   1. CATÉGORIES
───────────────────────────────────────────────────────── */

const CATEGORIES = [
  { key: "motif",  label: "Motif de voyage", icon: "✈️",  color: "#2E6A58" },
  { key: "duree",  label: "Durée du voyage",  icon: "📅",  color: "#B07D20" },
  { key: "lieux",  label: "Lieux du séjour",  icon: "📍",  color: "#2A5A88" },
  { key: "argent", label: "Argent",            icon: "💳",  color: "#8B3A2A" },
  { key: "autres", label: "Autres",            icon: "📋",  color: "#5A3A8B" },
];

const CAT_MAP = {
  "Motif de voyage": "motif",
  "Durée du voyage": "duree",
  "Lieux du séjour": "lieux",
  "Argent":          "argent",
  "Autres":          "autres",
};

/* ─────────────────────────────────────────────────────────
   2. MÉTADONNÉES LANGUES
───────────────────────────────────────────────────────── */

const LANG_META = {
  SQ: { slug:"albanais",    native:"Shqip",       region:"europe",       rtl:false, ttsLang:"sq-AL", flag:"🇦🇱" },
  DE: { slug:"allemand",    native:"Deutsch",      region:"europe",       rtl:false, ttsLang:"de-DE", flag:"🇩🇪" },
  EN: { slug:"anglais",     native:"English",      region:"europe",       rtl:false, ttsLang:"en-GB", flag:"🇬🇧" },
  AR: { slug:"arabe",       native:"العربية",       region:"moyen-orient", rtl:true,  ttsLang:"ar-SA", flag:"🇸🇦" },
  BS: { slug:"bosniaque",   native:"Bosanski",     region:"europe",       rtl:false, ttsLang:"bs-BA", flag:"🇧🇦" },
  ZH: { slug:"chinois",     native:"中文",          region:"asie",         rtl:false, ttsLang:"zh-CN", flag:"🇨🇳" },
  ES: { slug:"espagnol",    native:"Español",      region:"amerique",     rtl:false, ttsLang:"es-ES", flag:"🇪🇸" },
  KA: { slug:"georgien",    native:"ქართული",      region:"europe",       rtl:false, ttsLang:"ka-GE", flag:"🇬🇪" },
  EL: { slug:"grec",        native:"Ελληνικά",     region:"europe",       rtl:false, ttsLang:"el-GR", flag:"🇬🇷" },
  HE: { slug:"hebreu",      native:"עברית",         region:"moyen-orient", rtl:true,  ttsLang:"he-IL", flag:"🇮🇱" },
  IT: { slug:"italien",     native:"Italiano",     region:"europe",       rtl:false, ttsLang:"it-IT", flag:"🇮🇹" },
  MK: { slug:"macedonien",  native:"Македонски",   region:"europe",       rtl:false, ttsLang:"mk-MK", flag:"🇲🇰" },
  NL: { slug:"neerlandais", native:"Nederlands",   region:"europe",       rtl:false, ttsLang:"nl-NL", flag:"🇳🇱" },
  FA: { slug:"persan",      native:"فارسی",         region:"moyen-orient", rtl:true,  ttsLang:"fa-IR", flag:"🇮🇷" },
  PT: { slug:"portugais",   native:"Português",    region:"amerique",     rtl:false, ttsLang:"pt-PT", flag:"🇵🇹" },
  RO: { slug:"roumain",     native:"Română",       region:"europe",       rtl:false, ttsLang:"ro-RO", flag:"🇷🇴" },
  RU: { slug:"russe",       native:"Русский",      region:"europe",       rtl:false, ttsLang:"ru-RU", flag:"🇷🇺" },
  SR: { slug:"serbe",       native:"Srpski",       region:"europe",       rtl:false, ttsLang:"sr-RS", flag:"🇷🇸" },
  TR: { slug:"turc",        native:"Türkçe",       region:"europe",       rtl:false, ttsLang:"tr-TR", flag:"🇹🇷" },
  UK: { slug:"ukrainien",   native:"Українська",   region:"europe",       rtl:false, ttsLang:"uk-UA", flag:"🇺🇦" },
};

const LANG_ORDER = ["SQ","DE","EN","AR","BS","ZH","ES","KA","EL","HE","IT","MK","NL","FA","PT","RO","RU","SR","TR","UK"];

const LANG_NAMES = {
  SQ:"Albanais", DE:"Allemand", EN:"Anglais",  AR:"Arabe",      BS:"Bosniaque",
  ZH:"Chinois",  ES:"Espagnol", KA:"Géorgien", EL:"Grec",       HE:"Hébreu",
  IT:"Italien",  MK:"Macédonien", NL:"Néerlandais", FA:"Persan (Farsi)",
  PT:"Portugais", RO:"Roumain", RU:"Russe",    SR:"Serbe",      TR:"Turc",  UK:"Ukrainien",
};

/* ─────────────────────────────────────────────────────────
   3. QUESTIONS (20 par langue × 20 langues)
───────────────────────────────────────────────────────── */

const RAW_QUESTIONS = [
  // ── ALBANAIS (SQ)
  {id:"Q001",lang:"SQ",fr:"Pourquoi venir en Belgique ?",tr:"Pse të vini në Belgjikë ?",cat:"Motif de voyage"},
  {id:"Q002",lang:"SQ",fr:"Pour rendre visite à de la famille ?",tr:"Për të vizituar familjen?",cat:"Motif de voyage"},
  {id:"Q003",lang:"SQ",fr:"Pour faire du tourisme ?",tr:"Për turizëm?",cat:"Motif de voyage"},
  {id:"Q004",lang:"SQ",fr:"Pour le travail ?",tr:"Për punë?",cat:"Motif de voyage"},
  {id:"Q005",lang:"SQ",fr:"Montrez-moi votre contrat de travail ou votre invitation.",tr:"Më trego kontratën tënde të punës ose ftesën.",cat:"Motif de voyage"},
  {id:"Q006",lang:"SQ",fr:"Combien de temps restez vous en Europe ?",tr:"Sa gjatë do të qëndrosh në Evropë?",cat:"Durée du voyage"},
  {id:"Q007",lang:"SQ",fr:"Jours",tr:"Ditë",cat:"Durée du voyage"},
  {id:"Q008",lang:"SQ",fr:"Semaines",tr:"Javë",cat:"Durée du voyage"},
  {id:"Q009",lang:"SQ",fr:"Mois",tr:"Muaj",cat:"Durée du voyage"},
  {id:"Q010",lang:"SQ",fr:"Avez-vous un billet retour ?",tr:"Ke biletë kthimi?",cat:"Durée du voyage"},
  {id:"Q011",lang:"SQ",fr:"Montrez moi votre billet retour",tr:"Më trego biletën tënde të kthimit.",cat:"Durée du voyage"},
  {id:"Q012",lang:"SQ",fr:"Où allez vous dormir ?",tr:"Ku do të qëndrosh?",cat:"Lieux du séjour"},
  {id:"Q013",lang:"SQ",fr:"Chez de la famille ou des amis ?",tr:"Me familje apo me miq?",cat:"Lieux du séjour"},
  {id:"Q014",lang:"SQ",fr:"A l'hôtel ?",tr:"Në një hotel?",cat:"Lieux du séjour"},
  {id:"Q015",lang:"SQ",fr:"Montrez-moi la réservation d'hôtel",tr:"Më trego rezervimin e hotelit.",cat:"Lieux du séjour"},
  {id:"Q016",lang:"SQ",fr:"Avez-vous de l'argent liquide ou une carte de crédit ?",tr:"A ke para në dorë apo kartë krediti?",cat:"Argent"},
  {id:"Q017",lang:"SQ",fr:"Montrez-moi l'argent",tr:"Më trego paratë në dorë.",cat:"Argent"},
  {id:"Q018",lang:"SQ",fr:"Montrez-moi la carte de crédit",tr:"Më trego kartën e kreditit.",cat:"Argent"},
  {id:"Q019",lang:"SQ",fr:"Mettez les 4 doigts de la main droite sur la lumière verte",tr:"Vendosni katër gishtat e dorës së djathtë mbi dritën jeshile.",cat:"Autres"},
  {id:"Q020",lang:"SQ",fr:"Placez-vous devant la caméra",tr:"Qëndroni përpara kamerës.",cat:"Autres"},
  // ── ALLEMAND (DE)
  {id:"Q001",lang:"DE",fr:"Pourquoi venir en Belgique ?",tr:"Warum nach Belgien kommen.",cat:"Motif de voyage"},
  {id:"Q002",lang:"DE",fr:"Pour rendre visite à de la famille ?",tr:"Um Ihre Familie zu besuchen?",cat:"Motif de voyage"},
  {id:"Q003",lang:"DE",fr:"Pour faire du tourisme ?",tr:"Um Urlaub zu machen?",cat:"Motif de voyage"},
  {id:"Q004",lang:"DE",fr:"Pour le travail ?",tr:"Um zu arbeiten?",cat:"Motif de voyage"},
  {id:"Q005",lang:"DE",fr:"Montrez-moi votre contrat de travail ou votre invitation.",tr:"Zeigen Sie mir Ihren Arbeitsvertrag oder Ihre Einladung.",cat:"Motif de voyage"},
  {id:"Q006",lang:"DE",fr:"Combien de temps restez vous en Europe ?",tr:"Wie lange bleiben Sie in Europa?",cat:"Durée du voyage"},
  {id:"Q007",lang:"DE",fr:"Jours",tr:"Tage",cat:"Durée du voyage"},
  {id:"Q008",lang:"DE",fr:"Semaines",tr:"Wochen",cat:"Durée du voyage"},
  {id:"Q009",lang:"DE",fr:"Mois",tr:"Monate",cat:"Durée du voyage"},
  {id:"Q010",lang:"DE",fr:"Avez-vous un billet retour ?",tr:"Haben Sie ein Rückflugticket?",cat:"Durée du voyage"},
  {id:"Q011",lang:"DE",fr:"Montrez moi votre billet retour",tr:"Zeigen Sie mir Ihr Rückflugticket.",cat:"Durée du voyage"},
  {id:"Q012",lang:"DE",fr:"Où allez vous dormir ?",tr:"Wo werden Sie übernachten?",cat:"Lieux du séjour"},
  {id:"Q013",lang:"DE",fr:"Chez de la famille ou des amis ?",tr:"Bei Familie oder Freunden?",cat:"Lieux du séjour"},
  {id:"Q014",lang:"DE",fr:"A l'hôtel ?",tr:"Im Hotel?",cat:"Lieux du séjour"},
  {id:"Q015",lang:"DE",fr:"Montrez-moi la réservation d'hôtel",tr:"Zeigen Sie mir die Hotelreservierung",cat:"Lieux du séjour"},
  {id:"Q016",lang:"DE",fr:"Avez-vous de l'argent liquide ou une carte de crédit ?",tr:"Haben Sie Bargeld oder eine Kreditkarte?",cat:"Argent"},
  {id:"Q017",lang:"DE",fr:"Montrez-moi l'argent",tr:"Zeigen Sie mir das Geld",cat:"Argent"},
  {id:"Q018",lang:"DE",fr:"Montrez-moi la carte de crédit",tr:"Zeigen Sie mir die Kreditkarte",cat:"Argent"},
  {id:"Q019",lang:"DE",fr:"Mettez les 4 doigts de la main droite sur la lumière verte",tr:"Legen Sie die vier Finger Ihrer rechten Hand auf das grüne Licht.",cat:"Autres"},
  {id:"Q020",lang:"DE",fr:"Placez-vous devant la caméra",tr:"Stellen Sie sich vor die Kamera.",cat:"Autres"},
  // ── ANGLAIS (EN)
  {id:"Q001",lang:"EN",fr:"Pourquoi venir en Belgique ?",tr:"Why do you come to Belgium?",cat:"Motif de voyage"},
  {id:"Q002",lang:"EN",fr:"Pour rendre visite à de la famille ?",tr:"To visit your family?",cat:"Motif de voyage"},
  {id:"Q003",lang:"EN",fr:"Pour faire du tourisme ?",tr:"For tourism?",cat:"Motif de voyage"},
  {id:"Q004",lang:"EN",fr:"Pour le travail ?",tr:"For work?",cat:"Motif de voyage"},
  {id:"Q005",lang:"EN",fr:"Montrez-moi votre contrat de travail ou votre invitation.",tr:"Show me your employment contract or invitation.",cat:"Motif de voyage"},
  {id:"Q006",lang:"EN",fr:"Combien de temps restez vous en Europe ?",tr:"How long are you staying in Europe?",cat:"Durée du voyage"},
  {id:"Q007",lang:"EN",fr:"Jours",tr:"Days",cat:"Durée du voyage"},
  {id:"Q008",lang:"EN",fr:"Semaines",tr:"Weeks",cat:"Durée du voyage"},
  {id:"Q009",lang:"EN",fr:"Mois",tr:"Months",cat:"Durée du voyage"},
  {id:"Q010",lang:"EN",fr:"Avez-vous un billet retour ?",tr:"Do you have a return ticket?",cat:"Durée du voyage"},
  {id:"Q011",lang:"EN",fr:"Montrez moi votre billet retour",tr:"Show me your return ticket.",cat:"Durée du voyage"},
  {id:"Q012",lang:"EN",fr:"Où allez vous dormir ?",tr:"Where are you staying?",cat:"Lieux du séjour"},
  {id:"Q013",lang:"EN",fr:"Chez de la famille ou des amis ?",tr:"With family or friends?",cat:"Lieux du séjour"},
  {id:"Q014",lang:"EN",fr:"A l'hôtel ?",tr:"At a hotel?",cat:"Lieux du séjour"},
  {id:"Q015",lang:"EN",fr:"Montrez-moi la réservation d'hôtel",tr:"Show me the hotel reservation.",cat:"Lieux du séjour"},
  {id:"Q016",lang:"EN",fr:"Avez-vous de l'argent liquide ou une carte de crédit ?",tr:"Do you have cash or a credit card?",cat:"Argent"},
  {id:"Q017",lang:"EN",fr:"Montrez-moi l'argent",tr:"Show me the cash.",cat:"Argent"},
  {id:"Q018",lang:"EN",fr:"Montrez-moi la carte de crédit",tr:"Show me the credit card.",cat:"Argent"},
  {id:"Q019",lang:"EN",fr:"Mettez les 4 doigts de la main droite sur la lumière verte",tr:"Place the four fingers of your right hand on the green light.",cat:"Autres"},
  {id:"Q020",lang:"EN",fr:"Placez-vous devant la caméra",tr:"Stand in front of the camera.",cat:"Autres"},
  // ── ARABE (AR)
  {id:"Q001",lang:"AR",fr:"Pourquoi venir en Belgique ?",tr:"لماذا المجيء إلى بلجيكا؟",cat:"Motif de voyage"},
  {id:"Q002",lang:"AR",fr:"Pour rendre visite à de la famille ?",tr:"لزيارة عائلتك؟",cat:"Motif de voyage"},
  {id:"Q003",lang:"AR",fr:"Pour faire du tourisme ?",tr:"للسياحة؟",cat:"Motif de voyage"},
  {id:"Q004",lang:"AR",fr:"Pour le travail ?",tr:"للعمل؟",cat:"Motif de voyage"},
  {id:"Q005",lang:"AR",fr:"Montrez-moi votre contrat de travail ou votre invitation.",tr:"أرني عقد عملك أو دعوتك.",cat:"Motif de voyage"},
  {id:"Q006",lang:"AR",fr:"Combien de temps restez vous en Europe ?",tr:"كم من الوقت ستبقى في أوروبا؟",cat:"Durée du voyage"},
  {id:"Q007",lang:"AR",fr:"Jours",tr:"أيام",cat:"Durée du voyage"},
  {id:"Q008",lang:"AR",fr:"Semaines",tr:"أسابيع",cat:"Durée du voyage"},
  {id:"Q009",lang:"AR",fr:"Mois",tr:"أشهر",cat:"Durée du voyage"},
  {id:"Q010",lang:"AR",fr:"Avez-vous un billet retour ?",tr:"هل لديك تذكرة عودة؟",cat:"Durée du voyage"},
  {id:"Q011",lang:"AR",fr:"Montrez moi votre billet retour",tr:"أرني تذكرة عودتك.",cat:"Durée du voyage"},
  {id:"Q012",lang:"AR",fr:"Où allez vous dormir ?",tr:"أين ستنام؟",cat:"Lieux du séjour"},
  {id:"Q013",lang:"AR",fr:"Chez de la famille ou des amis ?",tr:"عند العائلة أو الأصدقاء؟",cat:"Lieux du séjour"},
  {id:"Q014",lang:"AR",fr:"A l'hôtel ?",tr:"في الفندق؟",cat:"Lieux du séjour"},
  {id:"Q015",lang:"AR",fr:"Montrez-moi la réservation d'hôtel",tr:"أرني حجز الفندق",cat:"Lieux du séjour"},
  {id:"Q016",lang:"AR",fr:"Avez-vous de l'argent liquide ou une carte de crédit ?",tr:"هل لديك نقود أو بطاقة ائتمان؟",cat:"Argent"},
  {id:"Q017",lang:"AR",fr:"Montrez-moi l'argent",tr:"أرني النقود",cat:"Argent"},
  {id:"Q018",lang:"AR",fr:"Montrez-moi la carte de crédit",tr:"أرني بطاقة الائتمان",cat:"Argent"},
  {id:"Q019",lang:"AR",fr:"Mettez les 4 doigts de la main droite sur la lumière verte",tr:"ضع أصابع يدك اليمنى الأربعة على الضوء الأخضر.",cat:"Autres"},
  {id:"Q020",lang:"AR",fr:"Placez-vous devant la caméra",tr:"قف أمام الكاميرا.",cat:"Autres"},
  // ── BOSNIAQUE (BS)
  {id:"Q001",lang:"BS",fr:"Pourquoi venir en Belgique ?",tr:"Zašto doći u Belgiju?",cat:"Motif de voyage"},
  {id:"Q002",lang:"BS",fr:"Pour rendre visite à de la famille ?",tr:"Da posjetite svoju porodicu?",cat:"Motif de voyage"},
  {id:"Q003",lang:"BS",fr:"Pour faire du tourisme ?",tr:"Za turizam?",cat:"Motif de voyage"},
  {id:"Q004",lang:"BS",fr:"Pour le travail ?",tr:"Za posao?",cat:"Motif de voyage"},
  {id:"Q005",lang:"BS",fr:"Montrez-moi votre contrat de travail ou votre invitation.",tr:"Pokazite mi vaš ugovor o radu ili pozivnicu.",cat:"Motif de voyage"},
  {id:"Q006",lang:"BS",fr:"Combien de temps restez vous en Europe ?",tr:"Koliko dugo boravite u Evropi?",cat:"Durée du voyage"},
  {id:"Q007",lang:"BS",fr:"Jours",tr:"Dani",cat:"Durée du voyage"},
  {id:"Q008",lang:"BS",fr:"Semaines",tr:"Sedmice",cat:"Durée du voyage"},
  {id:"Q009",lang:"BS",fr:"Mois",tr:"Mjeseci",cat:"Durée du voyage"},
  {id:"Q010",lang:"BS",fr:"Avez-vous un billet retour ?",tr:"Imate li povratnu kartu?",cat:"Durée du voyage"},
  {id:"Q011",lang:"BS",fr:"Montrez moi votre billet retour",tr:"Pokazite mi vašu povratnu kartu.",cat:"Durée du voyage"},
  {id:"Q012",lang:"BS",fr:"Où allez vous dormir ?",tr:"Gdje ćete boraviti?",cat:"Lieux du séjour"},
  {id:"Q013",lang:"BS",fr:"Chez de la famille ou des amis ?",tr:"Sa porodicom ili prijateljima?",cat:"Lieux du séjour"},
  {id:"Q014",lang:"BS",fr:"A l'hôtel ?",tr:"U hotelu?",cat:"Lieux du séjour"},
  {id:"Q015",lang:"BS",fr:"Montrez-moi la réservation d'hôtel",tr:"Pokažite mi rezervaciju hotela.",cat:"Lieux du séjour"},
  {id:"Q016",lang:"BS",fr:"Avez-vous de l'argent liquide ou une carte de crédit ?",tr:"Imate li gotovinu ili kreditnu karticu?",cat:"Argent"},
  {id:"Q017",lang:"BS",fr:"Montrez-moi l'argent",tr:"Pokažite mi gotovinu.",cat:"Argent"},
  {id:"Q018",lang:"BS",fr:"Montrez-moi la carte de crédit",tr:"Pokažite mi kreditnu karticu.",cat:"Argent"},
  {id:"Q019",lang:"BS",fr:"Mettez les 4 doigts de la main droite sur la lumière verte",tr:"Stavite četiri prsta desne ruke na zeleno svjetlo.",cat:"Autres"},
  {id:"Q020",lang:"BS",fr:"Placez-vous devant la caméra",tr:"Stajte ispred kamere.",cat:"Autres"},
  // ── CHINOIS (ZH)
  {id:"Q001",lang:"ZH",fr:"Pourquoi venir en Belgique ?",tr:"为什么来比利时？",cat:"Motif de voyage"},
  {id:"Q002",lang:"ZH",fr:"Pour rendre visite à de la famille ?",tr:"探亲？",cat:"Motif de voyage"},
  {id:"Q003",lang:"ZH",fr:"Pour faire du tourisme ?",tr:"旅游？",cat:"Motif de voyage"},
  {id:"Q004",lang:"ZH",fr:"Pour le travail ?",tr:"工作？",cat:"Motif de voyage"},
  {id:"Q005",lang:"ZH",fr:"Montrez-moi votre contrat de travail ou votre invitation.",tr:"请出示您的工作合同或邀请函。",cat:"Motif de voyage"},
  {id:"Q006",lang:"ZH",fr:"Combien de temps restez vous en Europe ?",tr:"您将在欧洲停留多久？",cat:"Durée du voyage"},
  {id:"Q007",lang:"ZH",fr:"Jours",tr:"几天",cat:"Durée du voyage"},
  {id:"Q008",lang:"ZH",fr:"Semaines",tr:"几周",cat:"Durée du voyage"},
  {id:"Q009",lang:"ZH",fr:"Mois",tr:"几个月",cat:"Durée du voyage"},
  {id:"Q010",lang:"ZH",fr:"Avez-vous un billet retour ?",tr:"您有返程机票吗？",cat:"Durée du voyage"},
  {id:"Q011",lang:"ZH",fr:"Montrez moi votre billet retour",tr:"请出示您的返程机票。",cat:"Durée du voyage"},
  {id:"Q012",lang:"ZH",fr:"Où allez vous dormir ?",tr:"你们打算住哪里？",cat:"Lieux du séjour"},
  {id:"Q013",lang:"ZH",fr:"Chez de la famille ou des amis ?",tr:"在亲戚或朋友家吗？",cat:"Lieux du séjour"},
  {id:"Q014",lang:"ZH",fr:"A l'hôtel ?",tr:"酒店？",cat:"Lieux du séjour"},
  {id:"Q015",lang:"ZH",fr:"Montrez-moi la réservation d'hôtel",tr:"给我看看酒店预订单",cat:"Lieux du séjour"},
  {id:"Q016",lang:"ZH",fr:"Avez-vous de l'argent liquide ou une carte de crédit ?",tr:"你们带现金还是信用卡？",cat:"Argent"},
  {id:"Q017",lang:"ZH",fr:"Montrez-moi l'argent",tr:"给我看看现金",cat:"Argent"},
  {id:"Q018",lang:"ZH",fr:"Montrez-moi la carte de crédit",tr:"给我看看信用卡",cat:"Argent"},
  {id:"Q019",lang:"ZH",fr:"Mettez les 4 doigts de la main droite sur la lumière verte",tr:"将右手的四根手指放在绿灯上。",cat:"Autres"},
  {id:"Q020",lang:"ZH",fr:"Placez-vous devant la caméra",tr:"站在摄像头前。",cat:"Autres"},
  // ── ESPAGNOL (ES)
  {id:"Q001",lang:"ES",fr:"Pourquoi venir en Belgique ?",tr:"¿Por qué viene a Bélgica?",cat:"Motif de voyage"},
  {id:"Q002",lang:"ES",fr:"Pour rendre visite à de la famille ?",tr:"¿Para visitar a tu familia?",cat:"Motif de voyage"},
  {id:"Q003",lang:"ES",fr:"Pour faire du tourisme ?",tr:"¿Para hacer turismo?",cat:"Motif de voyage"},
  {id:"Q004",lang:"ES",fr:"Pour le travail ?",tr:"¿Por trabajo?",cat:"Motif de voyage"},
  {id:"Q005",lang:"ES",fr:"Montrez-moi votre contrat de travail ou votre invitation.",tr:"Muéstrame tu contrato de trabajo o tu invitación.",cat:"Motif de voyage"},
  {id:"Q006",lang:"ES",fr:"Combien de temps restez vous en Europe ?",tr:"¿Cuánto tiempo te vas a quedar en Europa?",cat:"Durée du voyage"},
  {id:"Q007",lang:"ES",fr:"Jours",tr:"Días.",cat:"Durée du voyage"},
  {id:"Q008",lang:"ES",fr:"Semaines",tr:"Semanas.",cat:"Durée du voyage"},
  {id:"Q009",lang:"ES",fr:"Mois",tr:"Meses.",cat:"Durée du voyage"},
  {id:"Q010",lang:"ES",fr:"Avez-vous un billet retour ?",tr:"¿Tienes billete de vuelta?",cat:"Durée du voyage"},
  {id:"Q011",lang:"ES",fr:"Montrez moi votre billet retour",tr:"Muéstrame tu billete de vuelta.",cat:"Durée du voyage"},
  {id:"Q012",lang:"ES",fr:"Où allez vous dormir ?",tr:"¿Dónde vas a dormir?",cat:"Lieux du séjour"},
  {id:"Q013",lang:"ES",fr:"Chez de la famille ou des amis ?",tr:"¿En casa de familiares o amigos?",cat:"Lieux du séjour"},
  {id:"Q014",lang:"ES",fr:"A l'hôtel ?",tr:"¿En un hotel?",cat:"Lieux du séjour"},
  {id:"Q015",lang:"ES",fr:"Montrez-moi la réservation d'hôtel",tr:"Enséñame la reserva del hotel",cat:"Lieux du séjour"},
  {id:"Q016",lang:"ES",fr:"Avez-vous de l'argent liquide ou une carte de crédit ?",tr:"¿Tienes dinero en efectivo o una tarjeta de crédito?",cat:"Argent"},
  {id:"Q017",lang:"ES",fr:"Montrez-moi l'argent",tr:"Enséñame el dinero",cat:"Argent"},
  {id:"Q018",lang:"ES",fr:"Montrez-moi la carte de crédit",tr:"Enséñame la tarjeta de crédito",cat:"Argent"},
  {id:"Q019",lang:"ES",fr:"Mettez les 4 doigts de la main droite sur la lumière verte",tr:"Coloque los cuatro dedos de su mano derecha sobre la luz verde.",cat:"Autres"},
  {id:"Q020",lang:"ES",fr:"Placez-vous devant la caméra",tr:"Póngase delante de la cámara.",cat:"Autres"},
  // ── GÉORGIEN (KA)
  {id:"Q001",lang:"KA",fr:"Pourquoi venir en Belgique ?",tr:"რატომ ჩამოდი ბელგიაში ?",cat:"Motif de voyage"},
  {id:"Q002",lang:"KA",fr:"Pour rendre visite à de la famille ?",tr:"ოჯახის მოსანახულებლად?",cat:"Motif de voyage"},
  {id:"Q003",lang:"KA",fr:"Pour faire du tourisme ?",tr:"ტურიზმისთვის?",cat:"Motif de voyage"},
  {id:"Q004",lang:"KA",fr:"Pour le travail ?",tr:"სამუშაოდ?",cat:"Motif de voyage"},
  {id:"Q005",lang:"KA",fr:"Montrez-moi votre contrat de travail ou votre invitation.",tr:"მაჩვენეთ თქვენი შრომითი ხელშეკრულება ან მოსაწვევი.",cat:"Motif de voyage"},
  {id:"Q006",lang:"KA",fr:"Combien de temps restez vous en Europe ?",tr:"რამდენ ხანს რჩებით ევროპაში?",cat:"Durée du voyage"},
  {id:"Q007",lang:"KA",fr:"Jours",tr:"დღეები",cat:"Durée du voyage"},
  {id:"Q008",lang:"KA",fr:"Semaines",tr:"კვირები",cat:"Durée du voyage"},
  {id:"Q009",lang:"KA",fr:"Mois",tr:"თვეები",cat:"Durée du voyage"},
  {id:"Q010",lang:"KA",fr:"Avez-vous un billet retour ?",tr:"გაქვთ დასაბრუნებელი ბილეთი?",cat:"Durée du voyage"},
  {id:"Q011",lang:"KA",fr:"Montrez moi votre billet retour",tr:"მაჩვენეთ თქვენი დასაბრუნებელი ბილეთი.",cat:"Durée du voyage"},
  {id:"Q012",lang:"KA",fr:"Où allez vous dormir ?",tr:"სად დარჩებით?",cat:"Lieux du séjour"},
  {id:"Q013",lang:"KA",fr:"Chez de la famille ou des amis ?",tr:"ოჯახთან ერთად თუ მეგობრებთან?",cat:"Lieux du séjour"},
  {id:"Q014",lang:"KA",fr:"A l'hôtel ?",tr:"სასტუმროში?",cat:"Lieux du séjour"},
  {id:"Q015",lang:"KA",fr:"Montrez-moi la réservation d'hôtel",tr:"მაჩვენეთ სასტუმროს დაჯავშნის დამადასტურებელი დოკუმენტი.",cat:"Lieux du séjour"},
  {id:"Q016",lang:"KA",fr:"Avez-vous de l'argent liquide ou une carte de crédit ?",tr:"გაქვთ ნაღდი ფული ან საკრედიტო ბარათი?",cat:"Argent"},
  {id:"Q017",lang:"KA",fr:"Montrez-moi l'argent",tr:"მაჩვენეთ ნაღდი ფული.",cat:"Argent"},
  {id:"Q018",lang:"KA",fr:"Montrez-moi la carte de crédit",tr:"მაჩვენეთ საკრედიტო ბარათი.",cat:"Argent"},
  {id:"Q019",lang:"KA",fr:"Mettez les 4 doigts de la main droite sur la lumière verte",tr:"დადეთ თქვენი მარჯვენა ხელის ოთხი თითი მწვანე შუქზე.",cat:"Autres"},
  {id:"Q020",lang:"KA",fr:"Placez-vous devant la caméra",tr:"დადექით კამერის წინ.",cat:"Autres"},
  // ── GREC (EL)
  {id:"Q001",lang:"EL",fr:"Pourquoi venir en Belgique ?",tr:"Γιατί να έρθετε στο Βέλγιο;",cat:"Motif de voyage"},
  {id:"Q002",lang:"EL",fr:"Pour rendre visite à de la famille ?",tr:"Για να επισκεφθείτε την οικογένειά σας;",cat:"Motif de voyage"},
  {id:"Q003",lang:"EL",fr:"Pour faire du tourisme ?",tr:"Για τουρισμό;",cat:"Motif de voyage"},
  {id:"Q004",lang:"EL",fr:"Pour le travail ?",tr:"Για δουλειά;",cat:"Motif de voyage"},
  {id:"Q005",lang:"EL",fr:"Montrez-moi votre contrat de travail ou votre invitation.",tr:"Δείξτε μου τη σύμβαση εργασίας σας ή την πρόσκλησή σας.",cat:"Motif de voyage"},
  {id:"Q006",lang:"EL",fr:"Combien de temps restez vous en Europe ?",tr:"Πόσο καιρό θα μείνετε στην Ευρώπη;",cat:"Durée du voyage"},
  {id:"Q007",lang:"EL",fr:"Jours",tr:"Ημέρες",cat:"Durée du voyage"},
  {id:"Q008",lang:"EL",fr:"Semaines",tr:"Εβδομάδες",cat:"Durée du voyage"},
  {id:"Q009",lang:"EL",fr:"Mois",tr:"Μήνες",cat:"Durée du voyage"},
  {id:"Q010",lang:"EL",fr:"Avez-vous un billet retour ?",tr:"Έχετε εισιτήριο επιστροφής;",cat:"Durée du voyage"},
  {id:"Q011",lang:"EL",fr:"Montrez moi votre billet retour",tr:"Δείξτε μου το εισιτήριο επιστροφής σας.",cat:"Durée du voyage"},
  {id:"Q012",lang:"EL",fr:"Où allez vous dormir ?",tr:"Πού θα μείνετε;",cat:"Lieux du séjour"},
  {id:"Q013",lang:"EL",fr:"Chez de la famille ou des amis ?",tr:"Σε συγγενείς ή φίλους;",cat:"Lieux du séjour"},
  {id:"Q014",lang:"EL",fr:"A l'hôtel ?",tr:"Σε ξενοδοχείο;",cat:"Lieux du séjour"},
  {id:"Q015",lang:"EL",fr:"Montrez-moi la réservation d'hôtel",tr:"Δείξτε μου την κράτηση του ξενοδοχείου",cat:"Lieux du séjour"},
  {id:"Q016",lang:"EL",fr:"Avez-vous de l'argent liquide ou une carte de crédit ?",tr:"Έχετε μετρητά ή πιστωτική κάρτα;",cat:"Argent"},
  {id:"Q017",lang:"EL",fr:"Montrez-moi l'argent",tr:"Δείξτε μου τα χρήματα",cat:"Argent"},
  {id:"Q018",lang:"EL",fr:"Montrez-moi la carte de crédit",tr:"Δείξτε μου την πιστωτική κάρτα",cat:"Argent"},
  {id:"Q019",lang:"EL",fr:"Mettez les 4 doigts de la main droite sur la lumière verte",tr:"Τοποθετήστε τα τέσσερα δάχτυλα του δεξιού σας χεριού πάνω στο πράσινο φως.",cat:"Autres"},
  {id:"Q020",lang:"EL",fr:"Placez-vous devant la caméra",tr:"Σταθείτε μπροστά από την κάμερα.",cat:"Autres"},
  // ── HÉBREU (HE)
  {id:"Q001",lang:"HE",fr:"Pourquoi venir en Belgique ?",tr:"למה לבוא לבלגיה?",cat:"Motif de voyage"},
  {id:"Q002",lang:"HE",fr:"Pour rendre visite à de la famille ?",tr:"לבקר את המשפחה?",cat:"Motif de voyage"},
  {id:"Q003",lang:"HE",fr:"Pour faire du tourisme ?",tr:"לטייל?",cat:"Motif de voyage"},
  {id:"Q004",lang:"HE",fr:"Pour le travail ?",tr:"לעבודה?",cat:"Motif de voyage"},
  {id:"Q005",lang:"HE",fr:"Montrez-moi votre contrat de travail ou votre invitation.",tr:"הראו לי את חוזה העבודה או ההזמנה שלכם",cat:"Motif de voyage"},
  {id:"Q006",lang:"HE",fr:"Combien de temps restez vous en Europe ?",tr:"כמה זמן אתם מתכוונים להישאר באירופה?",cat:"Durée du voyage"},
  {id:"Q007",lang:"HE",fr:"Jours",tr:"ימים",cat:"Durée du voyage"},
  {id:"Q008",lang:"HE",fr:"Semaines",tr:"שבועות",cat:"Durée du voyage"},
  {id:"Q009",lang:"HE",fr:"Mois",tr:"חודשים",cat:"Durée du voyage"},
  {id:"Q010",lang:"HE",fr:"Avez-vous un billet retour ?",tr:"יש לכם כרטיס חזרה?",cat:"Durée du voyage"},
  {id:"Q011",lang:"HE",fr:"Montrez moi votre billet retour",tr:"הראו לי את כרטיס החזרה שלכם",cat:"Durée du voyage"},
  {id:"Q012",lang:"HE",fr:"Où allez vous dormir ?",tr:"איפה אתם מתכוונים לישון?",cat:"Lieux du séjour"},
  {id:"Q013",lang:"HE",fr:"Chez de la famille ou des amis ?",tr:"אצל משפחה או חברים?",cat:"Lieux du séjour"},
  {id:"Q014",lang:"HE",fr:"A l'hôtel ?",tr:"במלון?",cat:"Lieux du séjour"},
  {id:"Q015",lang:"HE",fr:"Montrez-moi la réservation d'hôtel",tr:"הראו לי את הזמנת המלון",cat:"Lieux du séjour"},
  {id:"Q016",lang:"HE",fr:"Avez-vous de l'argent liquide ou une carte de crédit ?",tr:"יש לכם מזומן או כרטיס אשראי?",cat:"Argent"},
  {id:"Q017",lang:"HE",fr:"Montrez-moi l'argent",tr:"הראו לי את הכסף",cat:"Argent"},
  {id:"Q018",lang:"HE",fr:"Montrez-moi la carte de crédit",tr:"הראו לי את כרטיס האשראי",cat:"Argent"},
  {id:"Q019",lang:"HE",fr:"Mettez les 4 doigts de la main droite sur la lumière verte",tr:"הניחו את ארבע אצבעות יד ימין על הנורית הירוקה.",cat:"Autres"},
  {id:"Q020",lang:"HE",fr:"Placez-vous devant la caméra",tr:"עמדו מול המצלמה.",cat:"Autres"},
  // ── ITALIEN (IT)
  {id:"Q001",lang:"IT",fr:"Pourquoi venir en Belgique ?",tr:"Perché venire in Belgio?",cat:"Motif de voyage"},
  {id:"Q002",lang:"IT",fr:"Pour rendre visite à de la famille ?",tr:"Per andare a trovare la tua famiglia?",cat:"Motif de voyage"},
  {id:"Q003",lang:"IT",fr:"Pour faire du tourisme ?",tr:"Per fare turismo?",cat:"Motif de voyage"},
  {id:"Q004",lang:"IT",fr:"Pour le travail ?",tr:"Per lavoro?",cat:"Motif de voyage"},
  {id:"Q005",lang:"IT",fr:"Montrez-moi votre contrat de travail ou votre invitation.",tr:"Mi mostri il suo contratto di lavoro o il suo invito.",cat:"Motif de voyage"},
  {id:"Q006",lang:"IT",fr:"Combien de temps restez vous en Europe ?",tr:"Quanto tempo rimarrà in Europa?",cat:"Durée du voyage"},
  {id:"Q007",lang:"IT",fr:"Jours",tr:"Giorni",cat:"Durée du voyage"},
  {id:"Q008",lang:"IT",fr:"Semaines",tr:"Settimane",cat:"Durée du voyage"},
  {id:"Q009",lang:"IT",fr:"Mois",tr:"Mesi",cat:"Durée du voyage"},
  {id:"Q010",lang:"IT",fr:"Avez-vous un billet retour ?",tr:"Ha un biglietto di ritorno?",cat:"Durée du voyage"},
  {id:"Q011",lang:"IT",fr:"Montrez moi votre billet retour",tr:"Mi mostri il suo biglietto di ritorno.",cat:"Durée du voyage"},
  {id:"Q012",lang:"IT",fr:"Où allez vous dormir ?",tr:"Dove dormirai?",cat:"Lieux du séjour"},
  {id:"Q013",lang:"IT",fr:"Chez de la famille ou des amis ?",tr:"Da familiari o amici?",cat:"Lieux du séjour"},
  {id:"Q014",lang:"IT",fr:"A l'hôtel ?",tr:"In hotel?",cat:"Lieux du séjour"},
  {id:"Q015",lang:"IT",fr:"Montrez-moi la réservation d'hôtel",tr:"Mostrami la prenotazione dell'hotel",cat:"Lieux du séjour"},
  {id:"Q016",lang:"IT",fr:"Avez-vous de l'argent liquide ou une carte de crédit ?",tr:"Hai contanti o una carta di credito?",cat:"Argent"},
  {id:"Q017",lang:"IT",fr:"Montrez-moi l'argent",tr:"Mostrami i contanti",cat:"Argent"},
  {id:"Q018",lang:"IT",fr:"Montrez-moi la carte de crédit",tr:"Mostrami la carta di credito",cat:"Argent"},
  {id:"Q019",lang:"IT",fr:"Mettez les 4 doigts de la main droite sur la lumière verte",tr:"Posizionate le quattro dita della mano destra sulla luce verde.",cat:"Autres"},
  {id:"Q020",lang:"IT",fr:"Placez-vous devant la caméra",tr:"Posizionatevi davanti alla telecamera.",cat:"Autres"},
  // ── MACÉDONIEN (MK)
  {id:"Q001",lang:"MK",fr:"Pourquoi venir en Belgique ?",tr:"Зошто да дојдете во Белгија?",cat:"Motif de voyage"},
  {id:"Q002",lang:"MK",fr:"Pour rendre visite à de la famille ?",tr:"Да го посетите вашето семејство?",cat:"Motif de voyage"},
  {id:"Q003",lang:"MK",fr:"Pour faire du tourisme ?",tr:"За туризам?",cat:"Motif de voyage"},
  {id:"Q004",lang:"MK",fr:"Pour le travail ?",tr:"За работа?",cat:"Motif de voyage"},
  {id:"Q005",lang:"MK",fr:"Montrez-moi votre contrat de travail ou votre invitation.",tr:"Покажете ми го вашиот договор за вработување или покана.",cat:"Motif de voyage"},
  {id:"Q006",lang:"MK",fr:"Combien de temps restez vous en Europe ?",tr:"Колку долго ќе престојувате во Европа?",cat:"Durée du voyage"},
  {id:"Q007",lang:"MK",fr:"Jours",tr:"Денови",cat:"Durée du voyage"},
  {id:"Q008",lang:"MK",fr:"Semaines",tr:"Недели",cat:"Durée du voyage"},
  {id:"Q009",lang:"MK",fr:"Mois",tr:"Месеци",cat:"Durée du voyage"},
  {id:"Q010",lang:"MK",fr:"Avez-vous un billet retour ?",tr:"Дали имате билет за повратна карта?",cat:"Durée du voyage"},
  {id:"Q011",lang:"MK",fr:"Montrez moi votre billet retour",tr:"Покажете ми ја вашата повратна карта.",cat:"Durée du voyage"},
  {id:"Q012",lang:"MK",fr:"Où allez vous dormir ?",tr:"Каде ќе престојувате?",cat:"Lieux du séjour"},
  {id:"Q013",lang:"MK",fr:"Chez de la famille ou des amis ?",tr:"Со семејство или со пријатели?",cat:"Lieux du séjour"},
  {id:"Q014",lang:"MK",fr:"A l'hôtel ?",tr:"Во хотел?",cat:"Lieux du séjour"},
  {id:"Q015",lang:"MK",fr:"Montrez-moi la réservation d'hôtel",tr:"Покажете ми ја хотелската резервација.",cat:"Lieux du séjour"},
  {id:"Q016",lang:"MK",fr:"Avez-vous de l'argent liquide ou une carte de crédit ?",tr:"Дали имате готовина или кредитна картичка?",cat:"Argent"},
  {id:"Q017",lang:"MK",fr:"Montrez-moi l'argent",tr:"Покажете ми ја готовината.",cat:"Argent"},
  {id:"Q018",lang:"MK",fr:"Montrez-moi la carte de crédit",tr:"Покажете ми ја кредитната картичка.",cat:"Argent"},
  {id:"Q019",lang:"MK",fr:"Mettez les 4 doigts de la main droite sur la lumière verte",tr:"Ставете ги четирите прста на вашата десна рака на зеленото светло.",cat:"Autres"},
  {id:"Q020",lang:"MK",fr:"Placez-vous devant la caméra",tr:"Стојте пред камерата.",cat:"Autres"},
  // ── NÉERLANDAIS (NL)
  {id:"Q001",lang:"NL",fr:"Pourquoi venir en Belgique ?",tr:"Waarom komt u naar België ?",cat:"Motif de voyage"},
  {id:"Q002",lang:"NL",fr:"Pour rendre visite à de la famille ?",tr:"Om uw familie te bezoeken?",cat:"Motif de voyage"},
  {id:"Q003",lang:"NL",fr:"Pour faire du tourisme ?",tr:"Om toerisme te bedrijven?",cat:"Motif de voyage"},
  {id:"Q004",lang:"NL",fr:"Pour le travail ?",tr:"Voor uw werk?",cat:"Motif de voyage"},
  {id:"Q005",lang:"NL",fr:"Montrez-moi votre contrat de travail ou votre invitation.",tr:"Laat me uw arbeidscontract of uw uitnodiging zien.",cat:"Motif de voyage"},
  {id:"Q006",lang:"NL",fr:"Combien de temps restez vous en Europe ?",tr:"Hoe lang blijft u in Europa?",cat:"Durée du voyage"},
  {id:"Q007",lang:"NL",fr:"Jours",tr:"Dagen",cat:"Durée du voyage"},
  {id:"Q008",lang:"NL",fr:"Semaines",tr:"Weken",cat:"Durée du voyage"},
  {id:"Q009",lang:"NL",fr:"Mois",tr:"Maanden",cat:"Durée du voyage"},
  {id:"Q010",lang:"NL",fr:"Avez-vous un billet retour ?",tr:"Heeft u een retourticket?",cat:"Durée du voyage"},
  {id:"Q011",lang:"NL",fr:"Montrez moi votre billet retour",tr:"Laat me uw retourticket zien.",cat:"Durée du voyage"},
  {id:"Q012",lang:"NL",fr:"Où allez vous dormir ?",tr:"Waar gaat u slapen?",cat:"Lieux du séjour"},
  {id:"Q013",lang:"NL",fr:"Chez de la famille ou des amis ?",tr:"Bij familie of vrienden?",cat:"Lieux du séjour"},
  {id:"Q014",lang:"NL",fr:"A l'hôtel ?",tr:"In een hotel?",cat:"Lieux du séjour"},
  {id:"Q015",lang:"NL",fr:"Montrez-moi la réservation d'hôtel",tr:"Laat me de hotelreservering zien",cat:"Lieux du séjour"},
  {id:"Q016",lang:"NL",fr:"Avez-vous de l'argent liquide ou une carte de crédit ?",tr:"Heeft u contant geld of een creditcard?",cat:"Argent"},
  {id:"Q017",lang:"NL",fr:"Montrez-moi l'argent",tr:"Laat me het geld zien",cat:"Argent"},
  {id:"Q018",lang:"NL",fr:"Montrez-moi la carte de crédit",tr:"Laat me de creditcard zien",cat:"Argent"},
  {id:"Q019",lang:"NL",fr:"Mettez les 4 doigts de la main droite sur la lumière verte",tr:"Plaats de vier vingers van uw rechterhand op het groene lampje.",cat:"Autres"},
  {id:"Q020",lang:"NL",fr:"Placez-vous devant la caméra",tr:"Ga voor de camera staan.",cat:"Autres"},
  // ── PERSAN (FA)
  {id:"Q001",lang:"FA",fr:"Pourquoi venir en Belgique ?",tr:"چرا به بلژیک بیایید؟",cat:"Motif de voyage"},
  {id:"Q002",lang:"FA",fr:"Pour rendre visite à de la famille ?",tr:"برای دیدار خانواده؟",cat:"Motif de voyage"},
  {id:"Q003",lang:"FA",fr:"Pour faire du tourisme ?",tr:"برای گردشگری؟",cat:"Motif de voyage"},
  {id:"Q004",lang:"FA",fr:"Pour le travail ?",tr:"برای کار؟",cat:"Motif de voyage"},
  {id:"Q005",lang:"FA",fr:"Montrez-moi votre contrat de travail ou votre invitation.",tr:"قرارداد استخدام یا دعوت‌نامه‌تان را به من نشان دهید.",cat:"Motif de voyage"},
  {id:"Q006",lang:"FA",fr:"Combien de temps restez vous en Europe ?",tr:"تا چه مدت در اروپا اقامت دارید؟",cat:"Durée du voyage"},
  {id:"Q007",lang:"FA",fr:"Jours",tr:"روزها",cat:"Durée du voyage"},
  {id:"Q008",lang:"FA",fr:"Semaines",tr:"هفته‌ها",cat:"Durée du voyage"},
  {id:"Q009",lang:"FA",fr:"Mois",tr:"ماهها",cat:"Durée du voyage"},
  {id:"Q010",lang:"FA",fr:"Avez-vous un billet retour ?",tr:"بلیط برگشت دارید؟",cat:"Durée du voyage"},
  {id:"Q011",lang:"FA",fr:"Montrez moi votre billet retour",tr:"بلیط برگشت خود را به من نشان دهید.",cat:"Durée du voyage"},
  {id:"Q012",lang:"FA",fr:"Où allez vous dormir ?",tr:"کجا اقامت خواهید داشت؟",cat:"Lieux du séjour"},
  {id:"Q013",lang:"FA",fr:"Chez de la famille ou des amis ?",tr:"با خانواده یا دوستان؟",cat:"Lieux du séjour"},
  {id:"Q014",lang:"FA",fr:"A l'hôtel ?",tr:"در هتل؟",cat:"Lieux du séjour"},
  {id:"Q015",lang:"FA",fr:"Montrez-moi la réservation d'hôtel",tr:"رزرو هتل را به من نشان دهید.",cat:"Lieux du séjour"},
  {id:"Q016",lang:"FA",fr:"Avez-vous de l'argent liquide ou une carte de crédit ?",tr:"آیا پول نقد یا کارت اعتباری دارید؟",cat:"Argent"},
  {id:"Q017",lang:"FA",fr:"Montrez-moi l'argent",tr:"پول نقد را به من نشان دهید.",cat:"Argent"},
  {id:"Q018",lang:"FA",fr:"Montrez-moi la carte de crédit",tr:"کارت اعتباری را به من نشان دهید.",cat:"Argent"},
  {id:"Q019",lang:"FA",fr:"Mettez les 4 doigts de la main droite sur la lumière verte",tr:"چهار انگشت دست راست خود را روی چراغ سبز قرار دهید.",cat:"Autres"},
  {id:"Q020",lang:"FA",fr:"Placez-vous devant la caméra",tr:"در مقابل دوربین بایستید.",cat:"Autres"},
  // ── PORTUGAIS (PT)
  {id:"Q001",lang:"PT",fr:"Pourquoi venir en Belgique ?",tr:"Porquê vir para a Bélgica ?",cat:"Motif de voyage"},
  {id:"Q002",lang:"PT",fr:"Pour rendre visite à de la famille ?",tr:"Para visitar a sua família?",cat:"Motif de voyage"},
  {id:"Q003",lang:"PT",fr:"Pour faire du tourisme ?",tr:"Para fazer turismo?",cat:"Motif de voyage"},
  {id:"Q004",lang:"PT",fr:"Pour le travail ?",tr:"Para trabalhar?",cat:"Motif de voyage"},
  {id:"Q005",lang:"PT",fr:"Montrez-moi votre contrat de travail ou votre invitation.",tr:"Mostre-me o seu contrato de trabalho ou o seu convite.",cat:"Motif de voyage"},
  {id:"Q006",lang:"PT",fr:"Combien de temps restez vous en Europe ?",tr:"Quanto tempo vai ficar na Europa?",cat:"Durée du voyage"},
  {id:"Q007",lang:"PT",fr:"Jours",tr:"Dias",cat:"Durée du voyage"},
  {id:"Q008",lang:"PT",fr:"Semaines",tr:"Semanas",cat:"Durée du voyage"},
  {id:"Q009",lang:"PT",fr:"Mois",tr:"Meses",cat:"Durée du voyage"},
  {id:"Q010",lang:"PT",fr:"Avez-vous un billet retour ?",tr:"Tem um bilhete de regresso?",cat:"Durée du voyage"},
  {id:"Q011",lang:"PT",fr:"Montrez moi votre billet retour",tr:"Mostre-me o seu bilhete de regresso.",cat:"Durée du voyage"},
  {id:"Q012",lang:"PT",fr:"Où allez vous dormir ?",tr:"Onde vai dormir?",cat:"Lieux du séjour"},
  {id:"Q013",lang:"PT",fr:"Chez de la famille ou des amis ?",tr:"Na casa de familiares ou amigos?",cat:"Lieux du séjour"},
  {id:"Q014",lang:"PT",fr:"A l'hôtel ?",tr:"Num hotel?",cat:"Lieux du séjour"},
  {id:"Q015",lang:"PT",fr:"Montrez-moi la réservation d'hôtel",tr:"Mostre-me a reserva do hotel",cat:"Lieux du séjour"},
  {id:"Q016",lang:"PT",fr:"Avez-vous de l'argent liqui